apiVersion: apps/v1
kind: Deployment
metadata:
  name: moverassign
  labels:
    app: moverassign
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moverassign
  template:
    metadata:
      labels:
        app: moverassign
    spec:
      containers:
        - name: moverassign
          image: skccteam03.azurecr.io/moverassign:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5