apiVersion: apps/v1
kind: Deployment
metadata:
  name: pickupmanage
  labels:
    app: pickupmanage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pickupmanage
  template:
    metadata:
      labels:
        app: pickupmanage
    spec:
      containers:
        - name: taximanage
          image: skccteam03.azurecr.io/pickupmanage:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5