server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: pickupcall
          uri: http://localhost:8081
          predicates:
            - Path=/pickupcalls/** 
        - id: pickupmanage
          uri: http://localhost:8082
          predicates:
            - Path=/pickupmanages/** 
        - id: pickupassign
          uri: http://localhost:8084
          predicates:
            - Path=/pickupassigns/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080

---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: taxicall
          uri: http://taxicall:8080
          predicates:
            - Path=/택시호출s/** 
        - id: taximanage
          uri: http://taximanage:8080
          predicates:
            - Path=/택시관리s/** 
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path= /택시호출정보/**
        - id: taxiassign
          uri: http://taxiassign:8080
          predicates:
            - Path=/택시할당s/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
