apiVersion: apps/v1
kind: Deployment
metadata:
  name: ascall
  labels:
    app: ascall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ascall
  template:
    metadata:
      labels:
        app: ascall
    spec:
      containers:
        - name: ascall
          image: skccteam03.azurecr.io/ascall:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5