server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: ascall
          uri: http://localhost:8081
          predicates:
            - Path=/ascalls/** 
        - id: asmanage
          uri: http://localhost:8082
          predicates:
            - Path=/asmanages/** 
        - id: asassign
          uri: http://localhost:8084
          predicates:
            - Path=/asassigns/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080

---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: ascall
          uri: http://ascall:8080
          predicates:
            - Path=/ascalls/** 
        - id: asmanage
          uri: http://asmanage:8080
          predicates:
            - Path=/asmanages/** 
        - id: asassign
          uri: http://asassign:8080
          predicates:
            - Path=/asassigns/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
