apiVersion: apps/v1
kind: Deployment
metadata:
  name: pickupassign
  labels:
    app: pickupassign
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pickupassign
  template:
    metadata:
      labels:
        app: pickupassign
    spec:
      containers:
        - name: taxiassign
          image: skccteam03.azurecr.io/pickupassign:v1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5